# Generated by Django 3.0.8 on 2020-08-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('entity', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('currency', models.CharField(max_length=100)),
                ('receipt', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('attempts', models.IntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razerpay_order_id', models.CharField(max_length=100)),
                ('razerpay_payment_id', models.CharField(max_length=100)),
                ('razerpay_signature', models.CharField(max_length=100)),
                ('successful', models.NullBooleanField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Order')),
            ],
        ),
    ]
