# Generated by Django 3.0.8 on 2020-08-31 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='razerpay_order_id',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='razerpay_payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='razerpay_signature',
            new_name='razorpay_signature',
        ),
    ]
