# Generated by Django 3.0.8 on 2020-09-03 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_auto_20200901_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='receipt',
            new_name='receipt_no',
        ),
        migrations.AddField(
            model_name='order',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='online_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lms.OnlineClassroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
