# Generated by Django 3.0.8 on 2020-09-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Codegnan User', 'verbose_name_plural': 'Codegnan Users'},
        ),
    ]
