# Generated by Django 3.0.8 on 2020-09-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20200902_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='question',
        ),
        migrations.AddField(
            model_name='certquestion',
            name='certificate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lms.Certificate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Course Overview'),
        ),
    ]
