# Generated by Django 3.0.8 on 2020-09-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20200902_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offer_expires',
            field=models.IntegerField(default=3),
        ),
    ]
