# Generated by Django 3.0.8 on 2020-09-02 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_course_offer_expires'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
            ],
        ),
    ]
