# Generated by Django 3.0.8 on 2020-09-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_onlineclassroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
