# Generated by Django 3.0.8 on 2020-09-03 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_auto_20200903_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='logo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.Reviews'),
            preserve_default=False,
        ),
    ]
