# Generated by Django 3.0.8 on 2020-09-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_testimonials_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentReviews',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='description',
        ),
    ]
