# Generated by Django 3.0.8 on 2020-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20200903_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getmoreinfo',
            name='course',
            field=models.CharField(max_length=50),
        ),
    ]
