# Generated by Django 3.0.8 on 2020-09-03 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_auto_20200904_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyCodegnan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('why', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Codegnan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('why', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.WhyCodegnan')),
            ],
        ),
    ]
