# Generated by Django 3.0.8 on 2020-09-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_codegnan_whycodegnan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codegnan',
            options={'verbose_name_plural': 'Codegnan'},
        ),
        migrations.AlterModelOptions(
            name='whycodegnan',
            options={'verbose_name_plural': 'Why Codegnan'},
        ),
    ]
