# Generated by Django 3.0.8 on 2020-09-03 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='title'),
        ),
    ]
